version: '3'

services:
  db:
    build:
      context: ./services/db
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./services/db/conf.d:/etc/mysql/conf.d
      - ./services/db/entrypoint:/docker-entrypoint-initdb.d
      - ./services/db/logs:/var/log/mysql
      - db-data:/var/lib/mysql
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: root
      # 初回起動時にアプリケーション用のDBユーザを自動作成するための設定
      # See also: "Environment Variables" section of https://hub.docker.com/_/mysql
      MYSQL_USER: example
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: example

volumes:
  db-data:
